### ISSUE TITLE
Modal grey background

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-design-system#24]
From @bgirardot in https://github.com/hotosm/oam-docs/issues/41. Moved here to track in core design system repo:  

> I think the back ground needs to be grayed out with the modal dialog content white background.
>
> Keeping the background white, but only blurred, does not define the area of the modal dialog content enough or indicate there is a new, important focus and message.
>
> It just looks like the page morphs, instead of clearly indicating this is a modal context switch, the main page is now "disabled" and the modal dialog content is now the focus and is "boxed" or "framed" so I know its exact extent.

**Comment by smit1678** [comment]
@bgirardot Can you describe the issue a bit more with the current design style? Is it that you can't read the text well? Can you show a screenshot of the issue?

**Comment by bgirardot** [comment]
I can read the modal text ok. 

The issue is that a modal dialog should clearly indicate what is going on. Typically this is done by grey'ing out the page and putting a dialog on top of that. So you can clearly see, the background has been "paused" while you deal with the dialog.

The way it works in oam design is that the background is just "blurred" with no color change. so if, as in the example, the background page is the same color as the modal dialog, it looks like the page sort of "morphs" into whatever the modal dialog is. Which is not visually clear enough what is going on.

I can try and make some examples to make it more clear.

But the main point is: Do not just blur the main page, but darken it, then put up the dialog box.

**Comment by smit1678** [comment]
@bgirardot Maybe we're looking at different issues of it. If you can post a screenshot of it, that would be helpful to get to the root of the issue. 

Here's how OAM feedback form is implemented: 

![modal](https://cloud.githubusercontent.com/assets/796838/23609652/ee01465a-0266-11e7-8ff7-dbe932d1ed7d.gif)

**Comment by bgirardot** [comment]
Not a great example, but how it works now:
![2017-03-06_13h21_27](https://cloud.githubusercontent.com/assets/265831/23609928/c4dfb752-0270-11e7-92e3-853174b9391e.png)


How I would like to see it work:
![2017-03-06_13h27_10](https://cloud.githubusercontent.com/assets/265831/23609942/d602c790-0270-11e7-8824-5b6252953e95.png)

**Comment by bgirardot** [comment]
Actually, I am not sure it should blur out now that I think about it. Because, while it is important to communicate the UI state change, the user might benefit from seeing clearly the underlying, now non functional page as part of their choice of response to the dialog. Not sure really, that would be bad design to cover up something potentially needed, but I think I would lean toward not blurring, just in case, even if we do not expect them to use the information on the original screen, it makes them feel better to see it before they deal with dialog. Still darken of course, just not blur. maybe. up to you.

**Comment by smit1678** [comment]
@bgirardot Yeah, is there a specific modal example using the oam-design-system where you see this is an issue? Maybe this is just an implementation issue.

**Comment by bgirardot** [comment]
The example on the design system examples is a great example of why it needs to be darkened.

I am curious why you are reluctant to just darken the underlying page to make the modal dialog more clear? What is the case for keeping it potentially difficult to differentiate the dialog from the underlying disabled page?

**Comment by bgirardot** [comment]
For reference:

http://www.uxforthemasses.com/overlays/
https://uxplanet.org/5-essential-ux-rules-for-dialog-design-4de258c22116#.6cpqucnno

**Comment by smit1678** [comment]
Only asking more detailed questions because it's meant to be a foundation for building upon based on how you want to implement it. The example uses a lot of text and so when using it in on a new project, the opacity may need to be increased or you use different colors on the page. It's also a fullscreen modal and so it's meant to be interacted with in a different way.

**Comment by bgirardot** [comment]
What is the difference between a full screen modal dialog and just a new screen?

**Comment by bgirardot** [comment]
Maybe we need two things then, one that is not full screen. The full screen one also has the UI issue of the close box being too far away from the dialog itself and not high enough contrast as well.

I guess that is the main issue here, the lack of high contrast between whatever is modal and the underlying page. Typically this is done by darkening the underlying page, but could be done other ways, for example a drop shadow around the dialog, or high contrast background on the dialog, or a high contrast border.
